name: litmath
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter_tex: ^4.0.3
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  provider: ^6.0.1
  deep_collection: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/Slide1.png
    - assets/imgs/Slide2.png
    - assets/imgs/loginBackground.png
    - assets/imgs/signupBackground.png
    - assets/imgs/preescolar.png
    - assets/imgs/primaria.png
    - assets/imgs/secundaria.png
    - assets/imgs/conteo.png
    - assets/imgs/division.png
    - assets/imgs/ecuaciones.png
    - assets/imgs/comparacion.png
    - assets/imgs/fracciones.png
    - assets/imgs/geometria.png
    - assets/imgs/multiplicacion.png
    - assets/imgs/reglatres.png
    - assets/imgs/resta.png
    - assets/imgs/series.png
    - assets/imgs/suma.png
    - assets/imgs/patrones.png
    - assets/imgs/corazon.png
    - assets/imgs/diamante.png
    - assets/imgs/triangulo.png
    - assets/imgs/primaria2.png
    - assets/imgs/tridimensional.png
    - assets/imgs/plano.png
    - assets/imgs/probabilidad.png
    - assets/imgs/patrones_screen_assets/patron_1.png
    - assets/imgs/patrones_screen_assets/patron_1_correcto.png
    - assets/imgs/patrones_screen_assets/patron_1_opcion_2.png
    - assets/imgs/patrones_screen_assets/patron_1_opcion_3.png
    - assets/imgs/patrones_screen_assets/patron_2.png
    - assets/imgs/patrones_screen_assets/patron_2_correcto.png
    - assets/imgs/patrones_screen_assets/patron_2_opcion_2.png
    - assets/imgs/patrones_screen_assets/patron_2_opcion_3.png
    - assets/imgs/patrones_screen_assets/patron_3.png
    - assets/imgs/patrones_screen_assets/patron_3_correcto.png
    - assets/imgs/patrones_screen_assets/patron_3_opcion_2.png
    - assets/imgs/patrones_screen_assets/patron_3_opcion_3.png
    - assets/imgs/patrones_screen_assets/patron_4.png
    - assets/imgs/patrones_screen_assets/patron_4_correcto.png
    - assets/imgs/patrones_screen_assets/patron_4_opcion_2.png
    - assets/imgs/patrones_screen_assets/patron_4_opcion_3.png
    - assets/imgs/patrones_screen_assets/patron_5.png
    - assets/imgs/patrones_screen_assets/patron_5_correcto.png
    - assets/imgs/patrones_screen_assets/patron_5_opcion_2.png
    - assets/imgs/patrones_screen_assets/patron_5_opcion_3.png
    - assets/imgs/shapes/circulo.png
    - assets/imgs/shapes/cuadrado.png
    - assets/imgs/shapes/decagono.png
    - assets/imgs/shapes/heptagono.png
    - assets/imgs/shapes/hexagono.png
    - assets/imgs/shapes/octagono.png
    - assets/imgs/shapes/pentagono.png
    - assets/imgs/shapes/rectangulo.png
    - assets/imgs/shapes/triangulo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf